ChainID = 999
CoinPrecision = 1000000
CoinSymbol = "ycc"
Title = "ycc"
version = "1.0.0.0"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "error"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"

[blockchain]
# 区块数据目录
dbPath = "datadir"
# 是否单节点运行
singleMode = true
# 是否关闭区块广播
disableBlockBroadcast = false

[p2p]
dbPath = "datadir/addrbook"
grpcLogFile = "grpc33.log"

[p2p.sub.dht]
# 分组通道, 同一个网络的channel必须相同
channel = 7
# p2p服务端口
port = 13701
#可以自定义设置连接节点
seeds = [
  #"/ip4/172.16.103.42/tcp/13701/p2p/16Uiu2HAkzrn3rYjvX8YVwevKw9rwFt5Yf6xG6wQFYMiihcYGKphZ",
]

[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = "localhost:7902"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = "localhost:7901"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["127.0.0.1"]

[consensus.sub.pos33]
bootPeers = [
  #"/ip4/172.16.103.42/tcp/10801/p2p/16Uiu2HAmErmNhtS145Lv5fe9FWrHSrNjPkp1eMLeLgi6t3sdr1of",
]
listenPort = 10801

[store]
dbPath = "datadir/kvmvcc"

[wallet]
dbPath = "wallet"
coinType = "eth"

[health]
listenAddr = "localhost:8709"
