# 需要发送的交易总量，例如：1000000表示总共发送一百万笔交易
TotalTx: 1000000
# DeployerAddr 扣费地址
# DeployerPrivkey 扣费地址对应的私钥
# ChainUrl 需要发送交易的远程链地址  扣费地址，私钥和链地址要一一对应
DeployerAddr: "0xa9e8d113d83a400e2d28209beefecb17fc76245e"
DeployerPrivkey: "0xb25802faad9555f45b8cef72020f270123ea239503d50c97e3b01747d48a1534"
ChainUrl: "122.224.77.186:9902"

# Chains为交易发送的链的进一步配置，可以包含多个链，表示TotalTx 笔交易会平均分布到Chains配置的链里面
# ParaName为链的名称
# ContractAddr为合约地址，当ContractAddr为空时，会自动部署合约，当ContractAddr有值时，会使用值对应的合约
Chains:
  - {
    ParaName: "user.p.para_pressuretest_1.",
    ContractAddr: "",
  }
  - {
    ParaName: "user.p.para_pressuretest_2.",
    ContractAddr: "",
  }
  - {
    ParaName: "user.p.para_pressuretest_3.",
    ContractAddr: "",
  }
  - {
    ParaName: "user.p.para_pressuretest_4.",
    ContractAddr: "",
  }
  - {
    ParaName: "user.p.para_pressuretest_5.",
    ContractAddr: "",
  }